//Pass Meds
fetch('https://app.lexigram.io/')
GET: Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdSI6Imx4ZzphcGkiLCJzYyI6WyJrZzpyZWFkIiwiZXh0cmFjdGlvbjpyZWFkIl0sImFpIjoiYXBpOjAxMDVkODQ4LTE0OGYtNDkxMC1jZTg4LTU0NGVjYWFkMGMxZCIsInVpIjoidXNlcjo5MDY4M2Q1NS1mYTRmLTczMmEtMzY4Ni03ZGY3ZDY3ZmJjNjciLCJpYXQiOjE2NDk1NDAzNDd9.V6a0A0T-kbQGGlp0Vt4lp2l8p-13iqZcTXb17QglNa0
.then(response => response.json)
.then(data => console.log(data))

// API Token
//eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdSI6Imx4ZzphcGkiLCJzYyI6WyJrZzpyZWFkIiwiZXh0cmFjdGlvbjpyZWFkIl0sImFpIjoiYXBpOjAxMDVkODQ4LTE0OGYtNDkxMC1jZTg4LTU0NGVjYWFkMGMxZCIsInVpIjoidXNlcjo5MDY4M2Q1NS1mYTRmLTczMmEtMzY4Ni03ZGY3ZDY3ZmJjNjciLCJpYXQiOjE2NDk1NDAzNDd9.V6a0A0T-kbQGGlp0Vt4lp2l8p-13iqZcTXb17QglNa0')

//API Authorization link
//curl -X GET -H 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdSI6Imx4ZzphcGkiLCJzYyI6WyJrZzpyZWFkIiwiZXh0cmFjdGlvbjpyZWFkIl0sImFpIjoiYXBpOjAxMDVkODQ4LTE0OGYtNDkxMC1jZTg4LTU0NGVjYWFkMGMxZCIsInVpIjoidXNlcjo5MDY4M2Q1NS1mYTRmLTczMmEtMzY4Ni03ZGY3ZDY3ZmJjNjciLCJpYXQiOjE2NDk1NDAzNDd9.V6a0A0T-kbQGGlp0Vt4lp2l8p-13iqZcTXb17QglNa0' https://api.lexigram.io/v1/lexigraph/search?q=diabetes